// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'firebase_options.dart';
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV797P34IIUF2La_ah95-rfpWh1892-u8',
    appId: '1:465566948631:web:437fffcf617a24a259ab52',
    messagingSenderId: '465566948631',
    projectId: 'school-forum-113e9',
    authDomain: 'school-forum-113e9.firebaseapp.com',
    storageBucket: 'school-forum-113e9.firebasestorage.app',
    measurementId: 'G-9PB78L99D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-5v9-KgKs6g2R7DoLVepDRfVRGdYB0es',
    appId: '1:465566948631:android:b73f625ba275899c59ab52',
    messagingSenderId: '465566948631',
    projectId: 'school-forum-113e9',
    storageBucket: 'school-forum-113e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx619dYgTphWLiBfF-3xS48_AXZ30LknY',
    appId: '1:465566948631:ios:450d2cf7ebf6e58459ab52',
    messagingSenderId: '465566948631',
    projectId: 'school-forum-113e9',
    storageBucket: 'school-forum-113e9.firebasestorage.app',
    iosBundleId: 'com.ucstt.schoolForum',
  );

}